[package]
name = "everscale-jrpc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
arc-swap = { version = "1.5", features = ["weak"] }
axum = { version = "0.6.0", features = ["http2"] }
axum-jrpc = "0.3.2"

everscale-jrpc-models = { path = "../models" }

nekoton-abi = { git = "https://github.com/broxus/nekoton.git", default-features = false }
parking_lot = { version = "0.12.0", features = ["hardware-lock-elision"] }
rustc-hash = "1.1"
serde_json = "1.0"
thiserror = "1.0"

ton-indexer = { git = "https://github.com/broxus/ton-indexer.git" }
ton_block = { git = "https://github.com/broxus/ton-labs-block.git" }
ton_types = { git = "https://github.com/broxus/ton-labs-types.git" }

tower = "0.4.12"
tower-http = { version = "0.3.0", features = ["compression-gzip"], optional = true }
tracing = "0.1.37"

[dev-dependencies]
hex = "0.4"
tokio = { version = "1", features = ["rt"] }

[features]
default = ["compression"]
compression = ["dep:tower-http"]
